<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Account extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'group_id', 'name', 'code', 'type', 'normal_balance', 'opening_balance',
        'is_bank_account', 'is_cash_account', 'branch_id', 'is_active', 'description',
    ];

    protected $casts = [
        'opening_balance' => 'decimal:2',
        'is_bank_account' => 'boolean',
        'is_cash_account' => 'boolean',
        'is_active' => 'boolean',
    ];

    public function group(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(AccountGroup::class, 'group_id');
    }

    public function journalLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(JournalEntryLine::class);
    }

    public function getBalanceAttribute(): float
    {
        $base = fn() => $this->journalLines()->whereHas('journalEntry', fn($q) => $q->where('status', 'posted'));
        $debits = $base()->sum('debit');
        $credits = $base()->sum('credit');
        if ($this->normal_balance === 'debit') {
            return (float) ($this->opening_balance + $debits - $credits);
        }
        return (float) ($this->opening_balance + $credits - $debits);
    }

    /**
     * Net amount paid down against this account's migrated opening balance,
     * still in effect (i.e. not since reversed by a bounced cheque). opening_balance
     * itself is never mutated by those payments — it stays a frozen historical
     * figure — so every customer/supplier-facing balance calculation must
     * subtract this separately to reflect payments actually received.
     *
     * Counts two kinds of entries: (1) the dedicated "record payment" feature
     * (opening_balance_payment / _reversed), and (2) a manual journal entry posted
     * straight to this account via Accounting > Journal Entries with no
     * reference_type — i.e. not auto-generated by any invoice/PO/GRN/return flow,
     * which already reach this account under their own reference_type ('invoice',
     * 'purchase_order', 'grn', 'purchase_return', 'cheque') and are excluded here
     * because they're already reflected via Invoice/PurchaseOrder balance_due —
     * counting them again here would double them into the balance.
     *
     * Polarity depends on normal_balance: a customer's receivable is debit-normal
     * (a payment received is a credit, so credit - debit is the amount paid down);
     * a supplier's payable is credit-normal (a payment made is a debit, so
     * debit - credit is the amount paid down). Getting this backwards would make
     * a supplier's balance grow instead of shrink when a payment is recorded.
     */
    public function openingBalancePaid(): float
    {
        $lines = $this->journalLines()
            ->whereHas('journalEntry', fn($q) => $q
                ->where('status', 'posted')
                ->where(function ($q2) {
                    $q2->whereIn('type', ['opening_balance_payment', 'opening_balance_payment_reversed'])
                       ->orWhere(function ($q3) {
                           $q3->where('type', 'manual')->whereNull('reference_type');
                       });
                }))
            ->get();

        return $this->normal_balance === 'credit'
            ? (float) $lines->sum(fn($l) => (float) $l->debit - (float) $l->credit)
            : (float) $lines->sum(fn($l) => (float) $l->credit - (float) $l->debit);
    }
}
